version: '3.8'

services:
  app:
    tty: true
    volumes:
      - ./templates/conf.d/:/etc/nginx/templates
      - ../:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: era_biz_nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=sapien.coder.vi
      - NGINX_PORT=80
    # networks:
    #     - nginxphp

  php:
    container_name: era_biz_php_fpm
    build:
      context: .
      dockerfile: Dockerfile.phplan
    volumes:
      - ../:/var/www/html
      - ./phpenv/php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000
    tty: true
    depends_on:
      - db
  db:
    image: postgres:12.13-bullseye
    container_name: postgres_db
    volumes:
      - ../db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: era_bizz
      POSTGRES_USER: postgres
